### ISSUE TITLE
kmer-counter generates the kmers composed of the letters more than GTAC

### ISSUE THREAD

**Issue by qianjia** [alexpreynolds/kmer-counter#2]
Hi there,
I am trying to use kmer-counter to generate the k-mers for every read, while the output (txt file) contains some k-mers that are composed of letters more than "G","T","A","C", as you can see the screenshot below.  I have no idea what happened, is there any way to fix it?
![screenshot from 2018-03-28 18-07-34](https://user-images.githubusercontent.com/18143321/38042108-c3bc1c34-32b3-11e8-9a06-e34ee42f88e2.png)

**Comment by alexpreynolds** [comment]
I probably just need to add support for the complements of degenerate bases. It shouldn't take long to do; I'll update this when things are patched.

**Comment by qianjia** [comment]
ok, when you update the new version, please let me know, thanks.

**Comment by alexpreynolds** [comment]
Updated reverse complement function with base complement table that accounts for IUPAC degenerate bases in commit b07795e

**Comment by alexpreynolds** [comment]
This patch should account for a broader variety of kmers. If you use this and run into any problems, feel free to update this issue.
