### ISSUE TITLE
K-mer length of 15 hanging

### ISSUE THREAD

**Issue by scchess** [alexpreynolds/kmer-counter#3]
I have a simple FASTA file (attached). My command:

    kmer-counter --fasta --k=6 <FASTA FILE>

nerver completed

[A.fasta.txt](https://github.com/alexpreynolds/kmer-counter/files/2227525/A.fasta.txt)

**Comment by alexpreynolds** [comment]
Made some changes in commit 399c4ccb60d9a80c7e2192e0e94c00294f288298 that should address this. Please let me know if you still run into problems.

```
$ time (./kmer-counter --fasta --k=15 ~/Downloads/A.fasta.txt)
>sp|Q64578|AT2A1_RAT Sarcoplasmic/endoplasmic reticulum calcium ATPase 1 OS=Rattus norvegicus OX=10116 GN=Atp2a1 PE=1 SV=1      LPLHHFEYCARTYHT:1 PEMPSYPPYHKIHLH:1 IVPGDIVEVAVGDKV:1 EPMTMALSVLVTIEM:1 ... RALDFTQWLMVLKIS:1

real    0m0.037s
user    0m0.002s
sys     0m0.003s
```

**Comment by alexpreynolds** [comment]
Also: Your chess app is good stuff.

**Comment by scchess** [comment]
Thanks. It worked. I've seen your posts about bioinformatics on discussion forums, so I recognized your name := ). I found this repo from https://www.biostars.org/p/247336/.

I like chess, and I make chess apps in my spare time, but my full-time job is bioinformatics something we share in common! Please share some feedback about my chess apps when you have some time.

Thanks.
