### ISSUE TITLE
Reverse complement?

### ISSUE THREAD

**Issue by suchapalaver** [alexpreynolds/kmer-counter#9]

**Comment by alexpreynolds** [comment]
Not sure what the question is. Maybe take a look at the `--rc` option? (See `--help` for more detail.) I'll close this up in the meantime.

**Comment by suchapalaver** [comment]
Thanks for the reply! Sorry for the vagueness. I can't seem to get it to work with --rc
Is this the right way to do it:
$ ./kmer-counter --fasta --k=6 --rc <fasta_file> --rc

**Comment by alexpreynolds** [comment]
You don't need to add `--rc` at the end:

```
$ ./kmer-counter --fasta --k=6 --rc <fasta_file>
```

**Comment by suchapalaver** [comment]
I'm sorry to bother you but I can't seem to get that to work. I can't find reverse complements in the output.
